---
title: "Thailand: COVID-19 Growth Dashboard"
date: "last updated: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
# DDC_WHO data
df_full <- read.csv("ddc_who_data.csv")
# ECDC data
#df_full <- read.csv("https://covid.ourworldindata.org/data/ecdc/full_data.csv")

# WHO data
#df_full <- read.csv("https://covid.ourworldindata.org/data/full_data.csv")
#df_new <- read.csv("https://covid.ourworldindata.org/data/new_cases.csv")
```

```{r setup, include=FALSE}
library(flexdashboard)
```

Row
-----------------------------------------------------------------------

```{r, include=FALSE}
library(tidyverse)

# total cases
full_thailand <- df_full %>% filter(location=="Thailand")
# add new columns
#full_thailand[,"Changes"] <- NA
#full_thailand[,"Growth_Factor"] <- NA

# calculate Changes (same as daily new_cases)
full_thailand <- full_thailand %>%
        arrange(date) %>%
        mutate(Changes = total_cases - lag(total_cases, default = first(total_cases)))

# calculate Growth Factor (cases)
full_thailand <- full_thailand %>%
        arrange(date) %>%
        mutate(Growth_Factor = Changes / lag(Changes, default = first(Changes)))

# convert Inf to NA - in Growth Factor column
full_thailand$Growth_Factor = ifelse(full_thailand$Growth_Factor==Inf, NA, full_thailand$Growth_Factor)

# calculate Growth Rate (cases)
full_thailand <- full_thailand %>% 
        arrange(date) %>% 
        mutate(Growth_Rate = ((total_cases - lag(total_cases, default = first(total_cases))) / lag(total_cases, default = first(total_cases)))*100)

# calculate Changes_PUI (patients under investigation; daily new tests)
full_thailand <- full_thailand %>% 
        arrange(date) %>% 
        mutate(Changes_PUI = pui - lag(pui, default = first(pui)))

# calculate Growth Factor (tests)
full_thailand <- full_thailand %>% 
        arrange(date) %>% 
        mutate(Growth_Factor_PUI = Changes_PUI / lag(Changes_PUI, default = first(Changes_PUI)))

# convert Inf to NA - in Growth_Factor_PUI column
full_thailand$Growth_Factor_PUI = ifelse(full_thailand$Growth_Factor_PUI==Inf, NA, full_thailand$Growth_Factor_PUI)

# calculate Growth Factor (Death)
full_thailand <- full_thailand %>%
        arrange(date) %>%
        mutate(Growth_Factor_Death = new_deaths / lag(new_deaths, default = first(new_deaths)))

```


### Growth Factor (Cases) Today

```{r}
# note: a growth factor of 1.15 implies doubling the total in 5 days
today_growth <- format(round(full_thailand$Growth_Factor[nrow(full_thailand)], 2), nsmall = 2)
valueBox(today_growth, color = ifelse(today_growth=="NA", "#808080", ifelse(today_growth < 1.15, "#33cc33", "#FF3300")))
```

### Growth Factor (Tests or PUI) Today

```{r}
test_growth <- format(round(full_thailand$Growth_Factor_PUI[nrow(full_thailand)], 2), nsmall = 2)
valueBox(test_growth, color = ifelse(test_growth=="NA", "#808080", ifelse(test_growth < 1.15, "orange", "#33cc33")))
```

### Growth Factor (Death) Today

```{r}
death_growth <- format(round(full_thailand$Growth_Factor_Death[nrow(full_thailand)], 2), nsmall = 0)
valueBox(death_growth, color = ifelse(death_growth=="NA", "#808080", ifelse(death_growth < 1.15, "#33cc33", "#FF3300")))

#yesterday_growth_rate <- format(round(full_thailand$Growth_Rate[nrow(full_thailand)], 2), nsmall = 0)
#valueBox(yesterday_growth_rate, color = "#36454F")
```


Row
-----------------------------------------------------------------------


### ยอดผู้ติดเชื้อเพิ่มวันนี้ // New Cases Today

```{r}
today_new <- format(round(full_thailand$new_cases[nrow(full_thailand)], 2), nsmall = 0)
valueBox(today_new, icon = "fa-pencil", color = "#336699")
```

### New Tests (PUI) Today
```{r}
test_new <- format(round(full_thailand$Changes_PUI[nrow(full_thailand)], 2), nsmall = 0)
valueBox(test_new, color = "#336699")
```

### New Deaths Today

```{r}
death_new <- format(round(full_thailand$new_deaths[nrow(full_thailand)], 2), nsmall = 0)
valueBox(death_new, color = "#336699")
```

Row
-----------------------------------------------------------------------

### Total Cases
```{r}
total_case <- format(round(full_thailand$total_cases[nrow(full_thailand)], 2), nsmall = 0)
valueBox(total_case, color = "#36454F")
```


### จำนวนคนที่ได้รับการตรวจสะสม //  Total Tests (Patients Under Investigation) 

```{r}
# data source: https://ddc.moph.go.th/viralpneumonia/eng/index.php
# in png file, need manual update
total_test <- full_thailand$pui[nrow(full_thailand)]
valueBox(total_test, color = "#36454F")
```

### Total Deaths

```{r}
total_death <- format(round(full_thailand$total_deaths[nrow(full_thailand)], 2), nsmall = 0)
valueBox(total_death, color = "#36454F")
```

Row
-----------------------------------------------------------------------
### New Cases Over Time

```{r}
thai_new_bar <- ggplot(data = full_thailand, aes(x=date)) + geom_bar(aes(y=new_cases), stat = "identity", size=2, fill="#336699", color = "white", alpha = 1.0) + labs(title = "New Cases", subtitle = "Jan 21 - present") + theme_classic() + theme(axis.text.x = element_blank())

renderPlot(thai_new_bar)
```

### Total Cases Over Time

```{r}
thai_total_bar <- ggplot(data = full_thailand, aes(x=date)) + geom_bar(aes(y=total_cases), stat = "identity", size=1, fill="#36454F", color = "white", alpha = 1.0) + labs(title = "Total Cases", subtitle = "Jan 21 - present") + theme_classic() + theme(axis.text.x = element_blank())

renderPlot(thai_total_bar)
```

Row
----------------------------------------------------------------------
### Tests Per Cases Over Time
```{r}
test_per_case <- ggplot(data = full_thailand, aes(x=date)) + geom_bar(aes(y=testpercase), stat = "identity", size=2, fill="#53868B", color = "white", alpha = 1.0) + labs(title = "Tests Per Case", subtitle = "Jan 21 - present") + theme_classic() + theme(axis.text.x = element_blank())

renderPlot(test_per_case)
```

### Total Tests Over Time

```{r}
test_total_bar <- ggplot(data = full_thailand, aes(x=date)) + geom_bar(aes(y=pui), stat = "identity", size=1, fill="#36454F", color = "white", alpha = 1.0) + labs(title = "Total Tests", subtitle = "Jan 21 - present") + theme_classic() + theme(axis.text.x = element_blank())

renderPlot(test_total_bar)
```
